### ISSUE TITLE
这个项目会自动签到吗

### ISSUE THREAD

**Issue by deeperwater** [LitttleHeroZZZX/hdu-library-booker#1]
学长您好，我试过了您的这个项目请问一下，我发现了一个问题：通过您这个项目占座的位置在微信上面的个人中心预约里面是不会显示的，也就是说没办法进行签到，那请问一下这个项目会自动签到吗

**Comment by LittleHeroZZZX** [comment]
可以在个人中心里看到的，软件是提示说约到了吗？如果个人中心没有，那就是没约上。另外，签到功能没办法实现。

**Comment by deeperwater** [comment]
软件运行显示运行成功，并且再通过公众号查看那个作文是不可约的状态，但是个人中心却查不到

**Comment by deeperwater** [comment]
对不起我的问题

**Comment by LittleHeroZZZX** [comment]
你可以试试我现在在用的[那个脚本](https://github.com/LittleHeroZZZX/hdu-library-killer)，原来这个好久之前写的，不太记得了。如果有这个脚本有问题可以再联系我~

**Comment by deeperwater** [comment]
大佬的脚本很好用
